export const ALL_GAMES = 'All'
export const LOAD_GAMES_COUNT = 4
export const BLUR_IMAGE_URL='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mO0MDKuBwACZQEevukm3wAAAABJRU5ErkJggg='